<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>uk.gov.moj.cpp.bpm</groupId>
        <artifactId>businessprocesses-query</artifactId>
        <version>25.104.4-M4-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>war</packaging>

    <artifactId>businessprocesses-query-api</artifactId>
    <properties>
        <cpp.service-component>QUERY_API</cpp.service-component>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>


    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>query-api</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.bpm</groupId>
            <artifactId>businessprocesses-query-view</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>test-utils-logging-simple</artifactId>
            <scope>test</scope>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.access-control</groupId>
            <artifactId>access-control-test-utils</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-enveloper-provider</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.generators</groupId>
                <artifactId>pojo-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pojo-generation</id>
                        <configuration>
                            <basePackageName>uk.gov.moj.cpp.businessprocesses
                            </basePackageName>
                            <sourceDirectory>src/raml/json/schema</sourceDirectory>
                            <outputDirectory>${project.build.directory}/generated-sources
                            </outputDirectory>
                            <generatorProperties implementation="uk.gov.justice.generation.pojo.core.PojoGeneratorProperties">
                                <plugins>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.typemodifying.ReferenceCustomReturnTypePlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.typemodifying.FormatCustomReturnTypePlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddHashcodeAndEqualsPlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddToStringMethodToClassPlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.MakeClassSerializablePlugin
                                    </plugin>
                                </plugins>
                                <typeMappings>
                                    <typeMapping>
                                        <name>uuid</name>
                                        <type>reference</type>
                                        <implementation>java.util.UUID</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date-time</name>
                                        <type>format</type>
                                        <implementation>java.time.ZonedDateTime</implementation>
                                    </typeMapping>
                                </typeMappings>
                            </generatorProperties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>
